artifact_location: /home/rajratan/Videos/ML_END_to_END/Data-Science/ec2-16-16-185-18.eu-north-1.compute.amazonaws.com/5000/0
creation_time: 1753647789997
experiment_id: '0'
last_update_time: 1753647789997
lifecycle_stage: active
name: Default
