artifact_uri: /home/rajratan/Videos/ML_END_to_END/Data-Science/ec2-16-16-185-18.eu-north-1.compute.amazonaws.com/5000/0/e58e07db6e94405ca946e83c6bf9aded/artifacts
end_time: 1753647790058
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: e58e07db6e94405ca946e83c6bf9aded
run_name: delightful-gnu-537
source_name: ''
source_type: 4
source_version: ''
start_time: 1753647790052
status: 3
tags: []
user_id: rajratan
